# Generated by Django 6.1 on 2026-09-02 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_sporttournament_match_tournament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sporttournament',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='sporttournament',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
